WIP fix: base off existing branch only if it exists and has an open pull request
all-contributors/app pull request #338
Opened 2021-01-07 17:02 UTC by hertzg

Fixes #336 

⚠️ WIP ⚠️

2021-12-30 16:21 UTC, Tyjuan1980 approved these changes

2021-12-30 16:21 UTC, Tyjuan1980 commented on lib/modules/repository.js
> -      const results = await this.octokit.pulls.list({
Looking good

2021-12-30 16:21 UTC, Tyjuan1980 commented on lib/modules/repository.js
> -        owner: this.owner,
Nicholas t walters

2021-12-30 16:21 UTC, Tyjuan1980 commented on test/unit/setup-repository.test.js
> +const { BranchNotFoundError } = require("../../lib/modules/errors");
Gracias

2022-09-06 12:39 UTC, tenshiAMD requested changes
@hertzg Hi, please rebase to `master` branch first and resolve all checks so we can proceed with this PR. Thanks!

2022-09-07 11:10 UTC, hertzg commented
Hey @tenshiAMD, unfortunately I don't have time to work on this pr now, but feel free to finish it if it's a priority right now or let me know and I can close this.

2022-09-12 19:28 UTC, tenshiAMD commented
@gr2m I think this is the current behavior now. Please check. Thanks.

2022-09-12 20:27 UTC, tenshiAMD commented
@hertzg Hi. Looks like the other tests got broken. Any ideas? What else are we missing here?

2022-09-12 23:24 UTC, gr2m commented
I'll try to have look this week but can't promise

2022-09-13 05:54 UTC, hertzg commented
@tenshiAMD Are you sure they just boke?

There’s a TODO on top of the PR

> TODO:
>
> - [ ] Save nock response snapshots for new pull request checks in happy paths

2022-09-13 07:09 UTC, tenshiAMD commented
> @tenshiAMD Are you sure they just broke?
> 
> There’s a TODO on top of the PR
> 
> > TODO:
> >
> > - [ ] Save nock response snapshots for new pull request checks in happy paths

@hertzg yes I already update the snapshots, you can review the recent checks in this PR

2022-09-17 11:12 UTC, tenshiAMD commented
Closing for now. Recreated to a new PR https://github.com/all-contributors/app/pull/415.

2022-09-17 11:12 UTC, closed without merging